import * as parsing from '../src/parsing.js';

test('parse Latin', () => {
  const xmlLines = [
    '<?xml version=\'1.0\' encoding=\'UTF-8\'?>',
    '<?xml-model href="http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng" schematypens="http://relaxng.org/ns/structure/1.0"?>',
    '',
    '<TEI xmlns="http://www.tei-c.org/ns/1.0">',
    '  <teiHeader>',
    '    <fileDesc>',
    '      <titleStmt>',
    '        <title type="work" n="Eleg.">Elegies</title>',
    '        <title type="sub">Machine readable text</title>',
    '        <author n="Prop.">Sextus Propertius</author>',
    '        <editor>Lucian Mueller</editor>',
    '<sponsor>Perseus Project, Tufts University</sponsor>',
    '    <principal>Gregory Crane</principal>',
    '    <respStmt>',
    '    <resp>Prepared under the supervision of</resp>',
    '      <name>Bridget Almas</name>',
    '    <name>Lisa Cerrato</name>',
    '    <name>William Merrill</name>',
    '    <name>David Smith</name>',
    '    </respStmt>',
    '<funder n="org:NEH">The National Endowment for the Humanities</funder>    ',
    '      </titleStmt>',
    '      <extent>about 35 Kb</extent>',
    '        <publicationStmt>',
    '    <publisher>Trustees of Tufts University</publisher>',
    '    <pubPlace>Medford, MA</pubPlace>',
    '    <authority>Perseus Project</authority>',
    '          <date type="release">2000-08-01</date>',
    '    </publicationStmt>',
    '      <sourceDesc>',
    '        <biblStruct>',
    '          <monogr>',
    '            <author>Propertius</author>',
    '            <title>Elegies</title>',
    '            <respStmt>',
    '              <name>Lucian Mueller</name>',
    '              <resp>editor</resp>',
    '            </respStmt>',
    '            <imprint>',
    '              <pubPlace>Leipzig</pubPlace>',
    '              <publisher>Teubner</publisher>',
    '              <date>1898</date>',
    '              <note>Machine readable text of this edition was posted on the Latin Library (http://www.thelatinlibrary.com) by Konrad Schroder</note>',
    '            </imprint>',
    '          </monogr>',
    '    ',
    '        </biblStruct>',
    '      </sourceDesc>',
    '    </fileDesc>',
    '',
    '    <encodingDesc>',
    '      <refsDecl n="CTS">',
    '        <cRefPattern n="line" matchPattern="(\\d+).(\\d+).(\\d+)" replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n=\'$1\']/tei:div[@n=\'$2\']//tei:l[@n=\'$3\'])">',
    '          <p>This pattern extracts book</p>',
    '        </cRefPattern>',
    '        <cRefPattern n="poem" matchPattern="(\\d+).(\\d+)" replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n=\'$1\']/tei:div[@n=\'$2\'])">',
    '          <p>This pattern extracts book</p>',
    '        </cRefPattern>',
    '        <cRefPattern n="book" matchPattern="(\\d+)" replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n=\'$1\'])">',
    '          <p>This pattern extracts book</p>',
    '        </cRefPattern>',
    '      </refsDecl>',
    '    </encodingDesc>',
    '',
    '    <profileDesc>',
    '      <langUsage>',
    '        <language ident="lat">Latin</language>',
    '      </langUsage>',
    '    </profileDesc>',
    '    <revisionDesc>',
    '      <change who="SI" when="1998-12-02">Text scanned, proofread and tagged by SI.</change>',
    '      <change who="SI" when="1998-12-08">Text of Prop. 1 proofread and tagged, added tei header which',
    '        needs revision; changed landando 1.4.1 to laudando</change>',
    '      <change who="AEM" when="2000-06-19">Unknown</change>',
    '      <change who="Thibault Clérice" when="2016-11-14">Epidoc, CapiTainS and line numbering</change>',
    '    </revisionDesc>',
    '  </teiHeader>',
    '<text>',
    '<body>',
    '  <div type="edition" n="urn:cts:latinLit:phi0620.phi001.perseus-lat3" xml:lang="lat">',
    '<div type="textpart" subtype="book" n="1">',
    '<div type="textpart" subtype="poem" n="1">',
    '<l n="1">Cynthia prima suis miserum me cepit ocellis,</l>',
    '</div>',
    '',
    '<div type="textpart" subtype="poem" n="2">',
    '<l n="1">Quid iuvat ornato procedere, vita, capillo</l>',
    '<l n="2">et tenuis Coa veste movere sinus,</l>',
    '</div>',
    '</div>',
    '<div type="textpart" subtype="book" n="2">',
    '<div type="textpart" subtype="poem" n="1">',
    '<l n="1">Quaeritis, unde mihi totiens scribantur amores,</l>',
    '<l n="2">unde meus veniat mollis in ore liber.</l>',
    '</div>',
    '</div>',
    '<div type="textpart" subtype="book" n="4">',
    '<div type="textpart" subtype="poem" n="1">',
    '<l n="101"><q>Iunonis facito uotum impetrabile</q> dixi:</l>',
    '</div>',
    '</div></div></body></text></TEI>'
  ]
  const xmlString = xmlLines.join('\n');
  const parsedObj = parsing.getParsedObj(xmlString);

  const title = parsing.getTitleAbbreviation(parsedObj);
  expect(title).toEqual('Eleg.');

  const author = parsing.getAuthorAbbreviation(parsedObj);
  expect(author).toEqual('Prop.');

  const structure = parsing.getCTSStructure(parsedObj);
  expect(structure).toEqual(['book', 'poem', 'line']);

  const tessLines = parsing.makeTess(parsedObj, author, title, structure).split('\n');
  const expecteds = [
    '<Prop. Eleg. 1.1.1>	Cynthia prima suis miserum me cepit ocellis,',
    '<Prop. Eleg. 1.2.1>	Quid iuvat ornato procedere, vita, capillo',
    '<Prop. Eleg. 1.2.2>	et tenuis Coa veste movere sinus,',
    '<Prop. Eleg. 2.1.1>	Quaeritis, unde mihi totiens scribantur amores,',
    '<Prop. Eleg. 2.1.2>	unde meus veniat mollis in ore liber.',
    '<Prop. Eleg. 4.1.101>	“Iunonis facito uotum impetrabile” dixi:'
  ]
  expect(tessLines).toEqual(expecteds);
})
